<testsuite name="testui.Resultador de un jugador de la palabra GATO" tests="4" errors="3" failures="0" skipped="1" time="44.677622" timestamp="2020-07-10T16:00:41.023757" hostname="DL001"><testcase classname="testui.Resultador de un jugador de la palabra GATO" name="un jugador gana una partida cuando ingresa correctamente las letras" status="failed" time="28.945283"><error type="WebDriverException" message="Message: chrome not reachable&#10;  (Session info: chrome=83.0.4103.116)&#10;">
<![CDATA[
Failing step: When ingresa correctamente todas las letras ... failed in 12.044s
Location: features/testui.feature:5
Traceback (most recent call last):
  File "c:\users\damian\appdata\local\programs\python\python38-32\lib\site-packages\behave\model.py", line 1329, in run
    match.run(runner.context)
  File "c:\users\damian\appdata\local\programs\python\python38-32\lib\site-packages\behave\matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features\steps\ganador_perfecto.py", line 22, in correct_words
    element = driver.find_element_by_id(i)
  File "c:\users\damian\appdata\local\programs\python\python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "c:\users\damian\appdata\local\programs\python\python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "c:\users\damian\appdata\local\programs\python\python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "c:\users\damian\appdata\local\programs\python\python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=83.0.4103.116)

]]>
</error><system-out>
<![CDATA[
@scenario.begin
  Scenario: un jugador gana una partida cuando ingresa correctamente las letras
    Given un jugador ... passed in 16.901s
    When ingresa correctamente todas las letras ... failed in 12.044s
    Then el resultado es ganador ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase><testcase classname="testui.Resultador de un jugador de la palabra GATO" name="un jugador pierde una partida cuando ingresa 6 veces las letras incorrectas" status="failed" time="12.080541"><error type="WebDriverException" message="Message: chrome not reachable&#10;  (Session info: chrome=83.0.4103.116)&#10;">
<![CDATA[
Failing step: Given un jugador ... failed in 12.081s
Location: features/testui.feature:9
Traceback (most recent call last):
  File "c:\users\damian\appdata\local\programs\python\python38-32\lib\site-packages\behave\model.py", line 1329, in run
    match.run(runner.context)
  File "c:\users\damian\appdata\local\programs\python\python38-32\lib\site-packages\behave\matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features\steps\ganador_perfecto.py", line 9, in welcome
    driver.get('http://localhost:5000')
  File "c:\users\damian\appdata\local\programs\python\python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "c:\users\damian\appdata\local\programs\python\python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "c:\users\damian\appdata\local\programs\python\python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=83.0.4103.116)

]]>
</error><system-out>
<![CDATA[
@scenario.begin
  Scenario: un jugador pierde una partida cuando ingresa 6 veces las letras incorrectas
    Given un jugador ... failed in 12.081s
    When ingresa 6 veces letras incorrectas ... skipped in 0.000s
    Then el resultado es perdedor ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase><testcase classname="testui.Resultador de un jugador de la palabra GATO" name="un jugador gana una partida cuando letras correctas e incorrectas en seis intentos" status="failed" time="3.651798"><error type="KeyboardInterrupt" message="">
<![CDATA[
Failing step: Given un jugador ... failed in 3.652s
Location: features/testui.feature:14
ABORTED: By user (KeyboardInterrupt).]]>
</error><system-out>
<![CDATA[
@scenario.begin
  Scenario: un jugador gana una partida cuando letras correctas e incorrectas en seis intentos
    Given un jugador ... failed in 3.652s
    When ingresa letras correctas e incorrectas ... skipped in 0.000s
    Then el resultado es ganador ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase><testcase classname="testui.Resultador de un jugador de la palabra GATO" name="Cuando un jugador gana y sigue aprentando letras el juego no se modifica" status="untested" time="0"><skipped /><system-out>
<![CDATA[
@scenario.begin
  Scenario: Cuando un jugador gana y sigue aprentando letras el juego no se modifica
    Given un ganador ... untested in 0.000s
    When ingresa 6 veces letras incorrectas ... untested in 0.000s
    Then el resultado es ganador ... untested in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase></testsuite>